# Site settings
title: Caj Jones
twitter_username: dellevelled
name: Caj Jones

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/DelleVelleD
 - title: LinkedIn
   url: https://www.linkedin.com/in/christopher-jones-86b694178/
 - title: Email
   url: mailto:delle.caj@gmail.com

#Any buzzword skills you want to include
skills:
 - C++
 - Engine Programming
 - Gameplay Programming
 - Unreal
 - Unity
 - AI Development
 - Python
 - Java
 - SQL
 - MEAN Stack

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Bachelor of Science (B.Sc.)
   start: 2021
   end: Ongoing
   employer: Software Development
   description: Georgia Gwinnett College

#Education is required
education:
- level: Grocery Clerk
  date: 2016
  subject: Publix Supermarkets
  school:
#- level: Bachelor of Science (B.Sc.)
#  date: 2021
#  subject: Software Development
#  school: Georgia Gwinnett College

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - SushiSalad/P3DPGE
 - SushiSalad/SMLabs
 - DelleVelleD/Rexaras5
 - DelleVelleD/Scheduler
 - supersand24/DungeonExplorer
 - DelleVelleD/ColoredBlocks
 - DelleVelleD/NieR2Blender_2.8

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am Christopher (Caj) Jones, a senior at Georgia Gwinnett College majoring in Computer Science with a focus in software design and a passion for game development.<br/><br/>
  I enjoy working on the projects that deal with building gameplay or engine functionality for games, but I also have a passion for building tools to be used by designers/artists.<br/><br/>
  I have worked on small projects either alone, with a partner, or a small group of friends and I am currently focused on a 3D game engine, <a href="https://github.com/SushiSalad/P3DPGE" target="_blank">P3DPGE</a>, that a friend and I are co-developing to learn deep engine knowledge as well as build games on in the future.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>C++</strong>: I primarily use C++ in my current projects for everything from engine programming to AI development.<br/><br/>
   <strong>Engine Programming</strong>: A friend and I have been developing a 3D physics engine on top of the <a href="https://github.com/OneLoneCoder/olcPixelGameEngine" target="_blank">PixelGameEngine</a> in C++ in order to learn 3D topics such as rendering, lighting, shaders, and physics.<br/><br/>
   <strong>Gameplay Programming</strong>: Using Unreal Engine, a friend and I are building a networked game with a focus on fast-paced air-strafing movement and simple character abilities. Additionally, I have worked on 2D map generation in Unity using the maze backtracing algorithm when working on DungeonExplorer, a small Pac-Man like game.<br/><br/>
   <strong>AI Development</strong>: I have been working on a needs-based AI approach to game AI in my project <a href="https://github.com/DelleVelleD/Rexaras5" target="_blank">Rexaras</a> in order to let AI make decisions that seem realistic.<br/><br/>
   <strong>Python</strong>: I have used Python for tool development when I was helping the Nier:Automata modding community in order to build a plugin for Blender which allowed for the importing/exporting of character models and animations.<br/><br/>
   <strong>Java</strong>: I learned Java all throughout school and this was the main language I started on for personal projects. Other than website projects, all other classes I took used Java.<br/><br/>
   <strong>Mean Stack</strong>: My team in my Software Development 1 course used the MEAN stack to develop a website and service for the professors at our college to register for courses they wished to take. <a href="https://ggc-scheduler.herokuapp.com/login-page" target="_blank">Scheduler</a>
