# Site settings
title: Caj Jones
twitter_username: dellevelled
name: Caj Jones

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/DelleVelleD
 - title: Email
   url: mailto:delle.caj@gmail.com


intro: |
  I am Caj (Christopher) Jones, a graduate from Georgia Gwinnett College with a degree in Computer Science and a passion for game development.<br/><br/>
  I enjoy working on the projects that deal with building gameplay, graphics, and engine functionality for games, but I also have a passion for building tools.<br/><br/>
  I have worked on projects either alone or with a small group of friends, and I am currently focused on a 3D graphics and game engine, <a href="https://github.com/DelleVelleD/deshi" target="_blank">deshi</a>, that a friend and I are co-developing to learn deep engine knowledge as well as build games/tools on in the future.<br/><br/>
  Email: delle.caj@gmail.com


#Any buzzword skills you want to include
skills:
 - C++
 - Python
 - Java
 - Engine Programming
 - Gameplay Programming
 - Unreal C++
 - Unreal Blueprints
 - Unreal Networking
 - Unity
 - AI Development
 - SQL
 - MEAN Stack


#NOTE(delle): i swapped the roles and education because their times were scuffed
#Work experience is required
roles:
 - title: Bachelor of Science (B.Sc.)
   start: 2021
   end: Ongoing
   employer: Software Development
   description: Georgia Gwinnett College
#Education is required
education:
- level: Grocery Clerk
  date: 2016
  subject: Publix Supermarkets
  school:
#- level: Bachelor of Science (B.Sc.)
#  date: 2021
#  subject: Software Development
#  school: Georgia Gwinnett College

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014


#List of interesting Github repo/projects to include - optional
github: |
 <a href="https://github.com/DelleVelleD/deshi" target="_blank">deshi C++ Game Engine</a><br/>
 A game engine for 3D physics and graphics using Vulkan and GLFW<br/><br/>
 <a href="https://github.com/SushiSalad/SMLabs" target="_blank">SMLabs UE4 Game</a><br/>
 An air-strafing and rope-grappling arena shooter designed in Unreal Engine<br/><br/>
 FreeRunners<br/>
 A direct-connect multiplayer, platforming, racing game designed in Unreal Engine<br/><br/>
 <a href="https://github.com/DelleVelleD/Rexaras5" target="_blank">Rexaras5 AI Simulation</a><br/>
 An attempt at making Needs-Based AI for a future game idea<br/><br/>
 <a href="https://github.com/DelleVelleD/Scheduler" target="_blank">Professor Course Scheduler</a><br/>
 A class project to make a course scheduler for professors at Georgia Gwinnett College<br/><br/>
 <a href="https://github.com/supersand24/DungeonExplorer" target="_blank">Dungeon Explorer</a><br/>
 A Unity game like pac-man, but with a randomly generated map and different movement<br/><br/>
 <a href="https://github.com/DelleVelleD/ColoredBlocks" target="_blank">Colored Blocks</a><br/>
 A game made in Java where the player must avoid certain colors<br/><br/>
 <a href="https://github.com/DelleVelleD/NieR2Blender_2.8" target="_blank">NieR2Blender Fork</a><br/>
 A fork of the Nier2Blender repository where I am adding animation import support to the blender plugin<br/>


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>C++</strong>: I primarily use C++ in my current projects for everything from engine programming to AI development.<br/><br/>
   <strong>Python</strong>: I have used Python for tool development when I was helping the Nier:Automata modding community in order to build a plugin for Blender which allowed for the importing/exporting of character models and animations.<br/><br/>
   <strong>Java</strong>: I learned Java all throughout school and this was the main language I started on for personal projects. Other than website projects, all other classes I took used Java.<br/><br/>
   <strong>Engine Programming</strong>: A friend and I have been developing a 3D physics engine in C++ in order to learn 3D topics such as rendering, lighting, shaders, and physics.<br/><br/>
   <strong>Gameplay Programming</strong>: Using Unreal Engine, a friend and I are building a networked game with a focus on fast-paced air-strafing movement and simple character abilities. Additionally, I have worked on 2D map generation in Unity using the maze backtracing algorithm when working on DungeonExplorer, a small Pac-Man like game.<br/><br/>
   <strong>Unreal</strong>: I have worked on two projects using Unreal Engine. One where I helped create the custom movement component and character abilities in C++. For the other, I was in charge of setting up multiplayer and the game instance, mode, etc for gameplay syncing which was mostly done in Blueprints and a bit in C++.<br/><br/>
   <strong>Unity</strong>: I have worked on a few small game projects in Unity both for school and outside of it, where I have worked with both 2D and 3D implementations.<br/><br/>
   <strong>AI Development</strong>: I have been working on a needs-based AI approach to game AI in my project <a href="https://github.com/DelleVelleD/Rexaras5" target="_blank">Rexaras</a> in order to let AI make decisions that seem realistic.<br/><br/>
   <strong>Mean Stack</strong>: My team in my Software Development 1 course used the MEAN stack to develop a website and service for the professors at our college to register for courses they wished to take. <a href="https://ggc-scheduler.herokuapp.com/login-page" target="_blank">Scheduler Demo</a>
